[package]
name = "maziq"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
crossterm = "0.27"
ctrlc = "3.4.1"
ratatui = "0.26"
