name = "hmziq"
description = "Default hmziq macOS developer workstation template."

software = [
  "homebrew",
  "xcode_clt",
  "brave",
  "firefox",
  "chrome",
  "cursor",
  "windsurf",
  "visual_studio_code",
  "zed_stable",
  "raycast",
  "docker_desktop",
  "postman",
  "yaak",
  "rustup",
  "rust_stable",
  "cargo_just",
  "cargo_binstall",
  "cargo_watch",
  "simple_http_server",
  "nvm",
  "bun",
  "go",
  "flutter",
  "android_studio",
  "react_native_cli",
  "electron_forge",
  "codex_cli",
  "claude_cli",
  "claude_multi_cli",
  "kimi_cli",
  "gemini_cli",
  "qwen_cli",
  "opencode_cli",
]
